import { describe, it, expect } from "vitest";
import { makeGuestToken, verifyGuestToken } from "../game-token";

// astro:env/server is aliased to src/__mocks__/astro-env-server.ts in vitest.config.ts

describe("makeGuestToken", () => {
  it("returns a 64-character hex string", () => {
    const token = makeGuestToken("guest-abc");
    expect(token).toMatch(/^[0-9a-f]{64}$/);
  });

  it("is deterministic — same id always produces the same token", () => {
    expect(makeGuestToken("guest-abc")).toBe(makeGuestToken("guest-abc"));
  });

  it("produces different tokens for different guest ids", () => {
    expect(makeGuestToken("guest-1")).not.toBe(makeGuestToken("guest-2"));
  });
});

describe("verifyGuestToken", () => {
  it("accepts a token generated by makeGuestToken for the same id", () => {
    const id = "some-guest-id";
    expect(verifyGuestToken(id, makeGuestToken(id))).toBe(true);
  });

  it("rejects a token generated for a different id", () => {
    expect(verifyGuestToken("id-a", makeGuestToken("id-b"))).toBe(false);
  });

  it("rejects a token with the wrong length", () => {
    // Length check is performed before the timing-safe comparison
    expect(verifyGuestToken("id-a", "short")).toBe(false);
  });

  it("rejects a token with one character changed (tampered)", () => {
    const id = "guest-xyz";
    const valid = makeGuestToken(id);
    const tampered = valid.slice(0, -1) + (valid.at(-1) === "f" ? "0" : "f");
    expect(verifyGuestToken(id, tampered)).toBe(false);
  });
});
